import Foundation

/// Typed DTOs for the owner WebAuthn registration wire (onboarding S3b).
///
/// The contract is pinned by the cross-language golden vectors
/// (`owner_webauthn_registration_vectors.json`, generated by theyos
/// `server-rs/tests/data/...`). Wire rules locked by those vectors:
///
/// - The wire is **canonical CBOR** (`HouseholdCBOR`), not JSON.
/// - `webauthn-rs` `Base64UrlSafeData` serializes as a **base64url TEXT string**
///   even in CBOR (URL-safe, no padding). So `challenge`, `user.id`, `rawId`,
///   `attestationObject`, `clientDataJSON`, and `id` are CBOR text here; the raw
///   `Data` conversion belongs at the future adapter boundary only.
/// - Wrapper fields are snake_case with the version renamed `v`; the embedded
///   webauthn types use their `serde` names (camelCase).
///
/// Two encode traps the server's decode->re-encode byte-equality check enforces:
/// - `response.transports` has no `skip_serializing_if`, so `nil` encodes as a
///   **present `null`**, never omitted.
/// - `credential.extensions` is always present; the default (all inners nil)
///   encodes as an **empty map `{}`**.
///
/// Scope: DTOs + parity only - no HTTP/PoP adapter and no `PasskeyProvider` here.
public enum OwnerWebauthnRegistrationDTOError: Error, Equatable, Sendable {
    case malformedCBOR(String)
}

// MARK: - CBOR read helpers

private extension HouseholdCBORValue {
    func cborMap(_ context: String) throws -> [String: HouseholdCBORValue] {
        guard case .map(let map) = self else {
            throw OwnerWebauthnRegistrationDTOError.malformedCBOR("\(context): expected map")
        }
        return map
    }

    func cborText(_ context: String) throws -> String {
        guard case .text(let text) = self else {
            throw OwnerWebauthnRegistrationDTOError.malformedCBOR("\(context): expected text string")
        }
        return text
    }

    func cborUnsigned(_ context: String) throws -> UInt64 {
        guard case .unsigned(let value) = self else {
            throw OwnerWebauthnRegistrationDTOError.malformedCBOR("\(context): expected unsigned integer")
        }
        return value
    }
}

private func cborRequire(
    _ map: [String: HouseholdCBORValue],
    _ key: String,
    _ context: String
) throws -> HouseholdCBORValue {
    guard let value = map[key] else {
        throw OwnerWebauthnRegistrationDTOError.malformedCBOR("\(context): missing key '\(key)'")
    }
    return value
}

private func cborUInt8(_ value: HouseholdCBORValue, _ context: String) throws -> UInt8 {
    let raw = try value.cborUnsigned(context)
    guard let narrowed = UInt8(exactly: raw) else {
        throw OwnerWebauthnRegistrationDTOError.malformedCBOR("\(context): \(raw) out of UInt8 range")
    }
    return narrowed
}

// MARK: - StartResponse (decode side)

/// `POST .../owner-webauthn/registration/start` request wrapper.
public struct OwnerWebauthnRegistrationStartRequest: Equatable, Sendable {
    public static let currentVersion: UInt8 = 1

    public let version: UInt8

    public init(version: UInt8 = Self.currentVersion) {
        self.version = version
    }

    public func canonicalBytes() -> Data {
        HouseholdCBOR.encode(.map([
            "v": .unsigned(UInt64(version)),
        ]))
    }
}

/// `rp` entity of the registration options.
public struct OwnerWebauthnRelyingParty: Decodable, Equatable, Sendable {
    public let id: String
    public let name: String

    public init(id: String, name: String) {
        self.id = id
        self.name = name
    }

    init(cbor: HouseholdCBORValue) throws {
        let map = try cbor.cborMap("rp")
        id = try cborRequire(map, "id", "rp").cborText("rp.id")
        name = try cborRequire(map, "name", "rp").cborText("rp.name")
    }
}

/// `user` entity. `id` is a base64url text string on the wire.
public struct OwnerWebauthnUserEntity: Decodable, Equatable, Sendable {
    public let id: String
    public let name: String
    public let displayName: String

    public init(id: String, name: String, displayName: String) {
        self.id = id
        self.name = name
        self.displayName = displayName
    }

    public var idData: Data? {
        PairingCrypto.base64URLDecode(id)
    }

    init(cbor: HouseholdCBORValue) throws {
        let map = try cbor.cborMap("user")
        id = try cborRequire(map, "id", "user").cborText("user.id")
        name = try cborRequire(map, "name", "user").cborText("user.name")
        displayName = try cborRequire(map, "displayName", "user").cborText("user.displayName")
    }
}

/// Lean view of `publicKey` - only the fields the future `PasskeyProvider`
/// consumes. Extra server-supplied fields (timeout, authenticatorSelection,
/// attestation, ...) are intentionally ignored on decode.
public struct OwnerWebauthnPublicKeyCredentialCreationOptions: Decodable, Equatable, Sendable {
    public let rp: OwnerWebauthnRelyingParty
    public let user: OwnerWebauthnUserEntity
    /// base64url text on the wire.
    public let challenge: String

    public init(
        rp: OwnerWebauthnRelyingParty,
        user: OwnerWebauthnUserEntity,
        challenge: String
    ) {
        self.rp = rp
        self.user = user
        self.challenge = challenge
    }

    public var challengeData: Data? {
        PairingCrypto.base64URLDecode(challenge)
    }

    init(cbor: HouseholdCBORValue) throws {
        let map = try cbor.cborMap("publicKey")
        rp = try OwnerWebauthnRelyingParty(cbor: cborRequire(map, "rp", "publicKey"))
        user = try OwnerWebauthnUserEntity(cbor: cborRequire(map, "user", "publicKey"))
        challenge = try cborRequire(map, "challenge", "publicKey").cborText("publicKey.challenge")
    }
}

public struct OwnerWebauthnCreationChallengeResponse: Decodable, Equatable, Sendable {
    public let publicKey: OwnerWebauthnPublicKeyCredentialCreationOptions

    public init(publicKey: OwnerWebauthnPublicKeyCredentialCreationOptions) {
        self.publicKey = publicKey
    }

    init(cbor: HouseholdCBORValue) throws {
        let map = try cbor.cborMap("options")
        publicKey = try OwnerWebauthnPublicKeyCredentialCreationOptions(
            cbor: cborRequire(map, "publicKey", "options")
        )
    }
}

/// `POST .../owner-webauthn/registration/start` response wrapper.
public struct OwnerWebauthnRegistrationStartResponse: Decodable, Equatable, Sendable {
    public let version: UInt8
    public let challengeID: String
    public let options: OwnerWebauthnCreationChallengeResponse

    enum CodingKeys: String, CodingKey {
        case version = "v"
        case challengeID = "challenge_id"
        case options
    }

    public init(
        version: UInt8,
        challengeID: String,
        options: OwnerWebauthnCreationChallengeResponse
    ) {
        self.version = version
        self.challengeID = challengeID
        self.options = options
    }

    /// Decode from canonical CBOR (the wire form the server emits).
    public init(cbor: HouseholdCBORValue) throws {
        let map = try cbor.cborMap("startResponse")
        version = try cborUInt8(cborRequire(map, "v", "startResponse"), "startResponse.v")
        challengeID = try cborRequire(map, "challenge_id", "startResponse").cborText("startResponse.challenge_id")
        options = try OwnerWebauthnCreationChallengeResponse(cbor: cborRequire(map, "options", "startResponse"))
    }
}

// MARK: - FinishRequest (encode side)

public struct OwnerWebauthnCredProps: Decodable, Equatable, Sendable {
    public let rk: Bool?

    public init(rk: Bool? = nil) {
        self.rk = rk
    }

    func cborValue() -> HouseholdCBORValue {
        var map: [String: HouseholdCBORValue] = [:]
        if let rk { map["rk"] = .bool(rk) }
        return .map(map)
    }
}

/// Client extension outputs. All inners are skip-if-nil, so the default value
/// canonical-encodes as an empty map `{}` (and the field itself is always
/// present on the credential).
public struct OwnerWebauthnRegistrationClientExtensionOutputs: Decodable, Equatable, Sendable {
    public let appid: Bool?
    public let credProps: OwnerWebauthnCredProps?
    public let hmacSecret: Bool?
    public let credProtect: String?
    public let minPinLength: UInt32?

    public init(
        appid: Bool? = nil,
        credProps: OwnerWebauthnCredProps? = nil,
        hmacSecret: Bool? = nil,
        credProtect: String? = nil,
        minPinLength: UInt32? = nil
    ) {
        self.appid = appid
        self.credProps = credProps
        self.hmacSecret = hmacSecret
        self.credProtect = credProtect
        self.minPinLength = minPinLength
    }

    func cborValue() -> HouseholdCBORValue {
        var map: [String: HouseholdCBORValue] = [:]
        if let appid { map["appid"] = .bool(appid) }
        if let credProps { map["credProps"] = credProps.cborValue() }
        if let hmacSecret { map["hmacSecret"] = .bool(hmacSecret) }
        if let credProtect { map["credProtect"] = .text(credProtect) }
        if let minPinLength { map["minPinLength"] = .unsigned(UInt64(minPinLength)) }
        return .map(map)
    }
}

/// `response` - the raw attestation. `attestationObject`/`clientDataJSON` are
/// base64url text on the wire; `transports` is present even when `nil` (null).
public struct OwnerWebauthnAuthenticatorAttestationResponse: Decodable, Equatable, Sendable {
    public let attestationObject: String
    public let clientDataJSON: String
    public let transports: [String]?

    public init(
        attestationObject: String,
        clientDataJSON: String,
        transports: [String]? = nil
    ) {
        self.attestationObject = attestationObject
        self.clientDataJSON = clientDataJSON
        self.transports = transports
    }

    public var attestationObjectData: Data? {
        PairingCrypto.base64URLDecode(attestationObject)
    }

    public var clientData: Data? {
        PairingCrypto.base64URLDecode(clientDataJSON)
    }

    func cborValue() -> HouseholdCBORValue {
        var map: [String: HouseholdCBORValue] = [
            "attestationObject": .text(attestationObject),
            "clientDataJSON": .text(clientDataJSON),
        ]
        // Trap: no skip_serializing_if on the Rust side - nil encodes as a
        // present `null`, never omitted.
        if let transports {
            map["transports"] = .array(transports.map { .text($0) })
        } else {
            map["transports"] = .null
        }
        return .map(map)
    }
}

/// `credential` - a `RegisterPublicKeyCredential`. `id` is base64url text;
/// `extensions` is always present (empty map when default).
public struct OwnerWebauthnRegisterCredential: Decodable, Equatable, Sendable {
    public let id: String
    public let rawId: String
    public let response: OwnerWebauthnAuthenticatorAttestationResponse
    public let type: String
    public let extensions: OwnerWebauthnRegistrationClientExtensionOutputs

    public init(
        id: String,
        rawId: String,
        response: OwnerWebauthnAuthenticatorAttestationResponse,
        type: String = "public-key",
        extensions: OwnerWebauthnRegistrationClientExtensionOutputs = .init()
    ) {
        self.id = id
        self.rawId = rawId
        self.response = response
        self.type = type
        self.extensions = extensions
    }

    public init(
        credentialID: Data,
        attestationObject: Data,
        clientDataJSON: Data,
        transports: [String]? = nil
    ) {
        let encodedCredentialID = PairingCrypto.base64URLEncode(credentialID)
        self.init(
            id: encodedCredentialID,
            rawId: encodedCredentialID,
            response: OwnerWebauthnAuthenticatorAttestationResponse(
                attestationObject: PairingCrypto.base64URLEncode(attestationObject),
                clientDataJSON: PairingCrypto.base64URLEncode(clientDataJSON),
                transports: transports
            )
        )
    }

    public var rawIdData: Data? {
        PairingCrypto.base64URLDecode(rawId)
    }

    func cborValue() -> HouseholdCBORValue {
        .map([
            "id": .text(id),
            "rawId": .text(rawId),
            "response": response.cborValue(),
            "type": .text(type),
            "extensions": extensions.cborValue(),
        ])
    }
}

/// `POST .../owner-webauthn/registration/finish` request wrapper.
public struct OwnerWebauthnRegistrationFinishRequest: Decodable, Equatable, Sendable {
    public let version: UInt8
    public let challengeID: String
    public let credential: OwnerWebauthnRegisterCredential

    enum CodingKeys: String, CodingKey {
        case version = "v"
        case challengeID = "challenge_id"
        case credential
    }

    public init(
        version: UInt8,
        challengeID: String,
        credential: OwnerWebauthnRegisterCredential
    ) {
        self.version = version
        self.challengeID = challengeID
        self.credential = credential
    }

    public func canonicalBytes() -> Data {
        HouseholdCBOR.encode(cborValue())
    }

    /// Canonical CBOR the client must send. The server decodes, re-encodes
    /// canonically and byte-compares, so this must match exactly.
    public func cborValue() -> HouseholdCBORValue {
        .map([
            "v": .unsigned(UInt64(version)),
            "challenge_id": .text(challengeID),
            "credential": credential.cborValue(),
        ])
    }
}
