// This file was autogenerated by some hot garbage in the `uniffi` crate.
// Trust me, you don't want to mess with it!

// swiftlint:disable all
import Foundation

// Depending on the consumer's build setup, the low-level FFI code
// might be in a separate module, or it might be compiled inline into
// this module. This is a bit of light hackery to work with both.
#if canImport(claw_share_bridge_rsFFI)
    import claw_share_bridge_rsFFI
#endif

private extension RustBuffer {
    /// Allocate a new buffer, copying the contents of a `UInt8` array.
    init(bytes: [UInt8]) {
        let rbuf = bytes.withUnsafeBufferPointer { ptr in
            RustBuffer.from(ptr)
        }
        self.init(capacity: rbuf.capacity, len: rbuf.len, data: rbuf.data)
    }

    static func empty() -> RustBuffer {
        RustBuffer(capacity: 0, len: 0, data: nil)
    }

    static func from(_ ptr: UnsafeBufferPointer<UInt8>) -> RustBuffer {
        try! rustCall { ffi_claw_share_bridge_rs_rustbuffer_from_bytes(ForeignBytes(bufferPointer: ptr), $0) }
    }

    /// Frees the buffer in place.
    /// The buffer must not be used after this is called.
    func deallocate() {
        try! rustCall { ffi_claw_share_bridge_rs_rustbuffer_free(self, $0) }
    }
}

private extension ForeignBytes {
    init(bufferPointer: UnsafeBufferPointer<UInt8>) {
        self.init(len: Int32(bufferPointer.count), data: bufferPointer.baseAddress)
    }
}

// For every type used in the interface, we provide helper methods for conveniently
// lifting and lowering that type from C-compatible data, and for reading and writing
// values of that type in a buffer.

// Helper classes/extensions that don't change.
// Someday, this will be in a library of its own.

private extension Data {
    init(rustBuffer: RustBuffer) {
        self.init(
            bytesNoCopy: rustBuffer.data!,
            count: Int(rustBuffer.len),
            deallocator: .none
        )
    }
}

// Define reader functionality.  Normally this would be defined in a class or
// struct, but we use standalone functions instead in order to make external
// types work.
//
// With external types, one swift source file needs to be able to call the read
// method on another source file's FfiConverter, but then what visibility
// should Reader have?
// - If Reader is fileprivate, then this means the read() must also
//   be fileprivate, which doesn't work with external types.
// - If Reader is internal/public, we'll get compile errors since both source
//   files will try define the same type.
//
// Instead, the read() method and these helper functions input a tuple of data

private func createReader(data: Data) -> (data: Data, offset: Data.Index) {
    (data: data, offset: 0)
}

/// Reads an integer at the current offset, in big-endian order, and advances
/// the offset on success. Throws if reading the integer would move the
/// offset past the end of the buffer.
private func readInt<T: FixedWidthInteger>(_ reader: inout (data: Data, offset: Data.Index)) throws -> T {
    let range = reader.offset ..< reader.offset + MemoryLayout<T>.size
    guard reader.data.count >= range.upperBound else {
        throw UniffiInternalError.bufferOverflow
    }
    if T.self == UInt8.self {
        let value = reader.data[reader.offset]
        reader.offset += 1
        return value as! T
    }
    var value: T = 0
    let _ = withUnsafeMutableBytes(of: &value) { reader.data.copyBytes(to: $0, from: range) }
    reader.offset = range.upperBound
    return value.bigEndian
}

/// Reads an arbitrary number of bytes, to be used to read
/// raw bytes, this is useful when lifting strings
private func readBytes(_ reader: inout (data: Data, offset: Data.Index), count: Int) throws -> [UInt8] {
    let range = reader.offset ..< (reader.offset + count)
    guard reader.data.count >= range.upperBound else {
        throw UniffiInternalError.bufferOverflow
    }
    var value = [UInt8](repeating: 0, count: count)
    value.withUnsafeMutableBufferPointer { buffer in
        reader.data.copyBytes(to: buffer, from: range)
    }
    reader.offset = range.upperBound
    return value
}

/// Reads a float at the current offset.
private func readFloat(_ reader: inout (data: Data, offset: Data.Index)) throws -> Float {
    return try Float(bitPattern: readInt(&reader))
}

/// Reads a float at the current offset.
private func readDouble(_ reader: inout (data: Data, offset: Data.Index)) throws -> Double {
    return try Double(bitPattern: readInt(&reader))
}

/// Indicates if the offset has reached the end of the buffer.
private func hasRemaining(_ reader: (data: Data, offset: Data.Index)) -> Bool {
    return reader.offset < reader.data.count
}

// Define writer functionality.  Normally this would be defined in a class or
// struct, but we use standalone functions instead in order to make external
// types work.  See the above discussion on Readers for details.

private func createWriter() -> [UInt8] {
    return []
}

private func writeBytes<S: Sequence>(_ writer: inout [UInt8], _ byteArr: S) where S.Element == UInt8 {
    writer.append(contentsOf: byteArr)
}

/// Writes an integer in big-endian order.
///
/// Warning: make sure what you are trying to write
/// is in the correct type!
private func writeInt<T: FixedWidthInteger>(_ writer: inout [UInt8], _ value: T) {
    var value = value.bigEndian
    withUnsafeBytes(of: &value) { writer.append(contentsOf: $0) }
}

private func writeFloat(_ writer: inout [UInt8], _ value: Float) {
    writeInt(&writer, value.bitPattern)
}

private func writeDouble(_ writer: inout [UInt8], _ value: Double) {
    writeInt(&writer, value.bitPattern)
}

/// Protocol for types that transfer other types across the FFI. This is
/// analogous to the Rust trait of the same name.
private protocol FfiConverter {
    associatedtype FfiType
    associatedtype SwiftType

    static func lift(_ value: FfiType) throws -> SwiftType
    static func lower(_ value: SwiftType) -> FfiType
    static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> SwiftType
    static func write(_ value: SwiftType, into buf: inout [UInt8])
}

/// Types conforming to `Primitive` pass themselves directly over the FFI.
private protocol FfiConverterPrimitive: FfiConverter where FfiType == SwiftType {}

extension FfiConverterPrimitive {
    #if swift(>=5.8)
        @_documentation(visibility: private)
    #endif
    public static func lift(_ value: FfiType) throws -> SwiftType {
        return value
    }

    #if swift(>=5.8)
        @_documentation(visibility: private)
    #endif
    public static func lower(_ value: SwiftType) -> FfiType {
        return value
    }
}

/// Types conforming to `FfiConverterRustBuffer` lift and lower into a `RustBuffer`.
/// Used for complex types where it's hard to write a custom lift/lower.
private protocol FfiConverterRustBuffer: FfiConverter where FfiType == RustBuffer {}

extension FfiConverterRustBuffer {
    #if swift(>=5.8)
        @_documentation(visibility: private)
    #endif
    public static func lift(_ buf: RustBuffer) throws -> SwiftType {
        var reader = createReader(data: Data(rustBuffer: buf))
        let value = try read(from: &reader)
        if hasRemaining(reader) {
            throw UniffiInternalError.incompleteData
        }
        buf.deallocate()
        return value
    }

    #if swift(>=5.8)
        @_documentation(visibility: private)
    #endif
    public static func lower(_ value: SwiftType) -> RustBuffer {
        var writer = createWriter()
        write(value, into: &writer)
        return RustBuffer(bytes: writer)
    }
}

/// An error type for FFI errors. These errors occur at the UniFFI level, not
/// the library level.
private enum UniffiInternalError: LocalizedError {
    case bufferOverflow
    case incompleteData
    case unexpectedOptionalTag
    case unexpectedEnumCase
    case unexpectedNullPointer
    case unexpectedRustCallStatusCode
    case unexpectedRustCallError
    case unexpectedStaleHandle
    case rustPanic(_ message: String)

    var errorDescription: String? {
        switch self {
        case .bufferOverflow: return "Reading the requested value would read past the end of the buffer"
        case .incompleteData: return "The buffer still has data after lifting its containing value"
        case .unexpectedOptionalTag: return "Unexpected optional tag; should be 0 or 1"
        case .unexpectedEnumCase: return "Raw enum value doesn't match any cases"
        case .unexpectedNullPointer: return "Raw pointer value was null"
        case .unexpectedRustCallStatusCode: return "Unexpected RustCallStatus code"
        case .unexpectedRustCallError: return "CALL_ERROR but no errorClass specified"
        case .unexpectedStaleHandle: return "The object in the handle map has been dropped already"
        case let .rustPanic(message): return message
        }
    }
}

private extension NSLock {
    func withLock<T>(f: () throws -> T) rethrows -> T {
        lock()
        defer { self.unlock() }
        return try f()
    }
}

private let CALL_SUCCESS: Int8 = 0
private let CALL_ERROR: Int8 = 1
private let CALL_UNEXPECTED_ERROR: Int8 = 2
private let CALL_CANCELLED: Int8 = 3

private extension RustCallStatus {
    init() {
        self.init(
            code: CALL_SUCCESS,
            errorBuf: RustBuffer(
                capacity: 0,
                len: 0,
                data: nil
            )
        )
    }
}

private func rustCall<T>(_ callback: (UnsafeMutablePointer<RustCallStatus>) -> T) throws -> T {
    let neverThrow: ((RustBuffer) throws -> Never)? = nil
    return try makeRustCall(callback, errorHandler: neverThrow)
}

private func rustCallWithError<T, E: Swift.Error>(
    _ errorHandler: @escaping (RustBuffer) throws -> E,
    _ callback: (UnsafeMutablePointer<RustCallStatus>) -> T
) throws -> T {
    try makeRustCall(callback, errorHandler: errorHandler)
}

private func makeRustCall<T, E: Swift.Error>(
    _ callback: (UnsafeMutablePointer<RustCallStatus>) -> T,
    errorHandler: ((RustBuffer) throws -> E)?
) throws -> T {
    uniffiEnsureInitialized()
    var callStatus = RustCallStatus()
    let returnedVal = callback(&callStatus)
    try uniffiCheckCallStatus(callStatus: callStatus, errorHandler: errorHandler)
    return returnedVal
}

private func uniffiCheckCallStatus<E: Swift.Error>(
    callStatus: RustCallStatus,
    errorHandler: ((RustBuffer) throws -> E)?
) throws {
    switch callStatus.code {
    case CALL_SUCCESS:
        return

    case CALL_ERROR:
        if let errorHandler = errorHandler {
            throw try errorHandler(callStatus.errorBuf)
        } else {
            callStatus.errorBuf.deallocate()
            throw UniffiInternalError.unexpectedRustCallError
        }

    case CALL_UNEXPECTED_ERROR:
        // When the rust code sees a panic, it tries to construct a RustBuffer
        // with the message.  But if that code panics, then it just sends back
        // an empty buffer.
        if callStatus.errorBuf.len > 0 {
            throw try UniffiInternalError.rustPanic(FfiConverterString.lift(callStatus.errorBuf))
        } else {
            callStatus.errorBuf.deallocate()
            throw UniffiInternalError.rustPanic("Rust panic")
        }

    case CALL_CANCELLED:
        fatalError("Cancellation not supported yet")

    default:
        throw UniffiInternalError.unexpectedRustCallStatusCode
    }
}

private func uniffiTraitInterfaceCall<T>(
    callStatus: UnsafeMutablePointer<RustCallStatus>,
    makeCall: () throws -> T,
    writeReturn: (T) -> Void
) {
    do {
        try writeReturn(makeCall())
    } catch {
        callStatus.pointee.code = CALL_UNEXPECTED_ERROR
        callStatus.pointee.errorBuf = FfiConverterString.lower(String(describing: error))
    }
}

private func uniffiTraitInterfaceCallWithError<T, E>(
    callStatus: UnsafeMutablePointer<RustCallStatus>,
    makeCall: () throws -> T,
    writeReturn: (T) -> Void,
    lowerError: (E) -> RustBuffer
) {
    do {
        try writeReturn(makeCall())
    } catch let error as E {
        callStatus.pointee.code = CALL_ERROR
        callStatus.pointee.errorBuf = lowerError(error)
    } catch {
        callStatus.pointee.code = CALL_UNEXPECTED_ERROR
        callStatus.pointee.errorBuf = FfiConverterString.lower(String(describing: error))
    }
}

private class UniffiHandleMap<T> {
    private var map: [UInt64: T] = [:]
    private let lock = NSLock()
    private var currentHandle: UInt64 = 1

    func insert(obj: T) -> UInt64 {
        lock.withLock {
            let handle = currentHandle
            currentHandle += 1
            map[handle] = obj
            return handle
        }
    }

    func get(handle: UInt64) throws -> T {
        try lock.withLock {
            guard let obj = map[handle] else {
                throw UniffiInternalError.unexpectedStaleHandle
            }
            return obj
        }
    }

    @discardableResult
    func remove(handle: UInt64) throws -> T {
        try lock.withLock {
            guard let obj = map.removeValue(forKey: handle) else {
                throw UniffiInternalError.unexpectedStaleHandle
            }
            return obj
        }
    }

    var count: Int {
        map.count
    }
}

// Public interface members begin here.

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
private struct FfiConverterUInt16: FfiConverterPrimitive {
    typealias FfiType = UInt16
    typealias SwiftType = UInt16

    static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> UInt16 {
        return try lift(readInt(&buf))
    }

    static func write(_ value: SwiftType, into buf: inout [UInt8]) {
        writeInt(&buf, lower(value))
    }
}

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
private struct FfiConverterUInt64: FfiConverterPrimitive {
    typealias FfiType = UInt64
    typealias SwiftType = UInt64

    static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> UInt64 {
        return try lift(readInt(&buf))
    }

    static func write(_ value: SwiftType, into buf: inout [UInt8]) {
        writeInt(&buf, lower(value))
    }
}

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
private struct FfiConverterString: FfiConverter {
    typealias SwiftType = String
    typealias FfiType = RustBuffer

    static func lift(_ value: RustBuffer) throws -> String {
        defer {
            value.deallocate()
        }
        if value.data == nil {
            return String()
        }
        let bytes = UnsafeBufferPointer<UInt8>(start: value.data!, count: Int(value.len))
        return String(bytes: bytes, encoding: String.Encoding.utf8)!
    }

    static func lower(_ value: String) -> RustBuffer {
        return value.utf8CString.withUnsafeBufferPointer { ptr in
            // The swift string gives us int8_t, we want uint8_t.
            ptr.withMemoryRebound(to: UInt8.self) { ptr in
                // The swift string gives us a trailing null byte, we don't want it.
                let buf = UnsafeBufferPointer(rebasing: ptr.prefix(upTo: ptr.count - 1))
                return RustBuffer.from(buf)
            }
        }
    }

    static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> String {
        let len: Int32 = try readInt(&buf)
        return try String(bytes: readBytes(&buf, count: Int(len)), encoding: String.Encoding.utf8)!
    }

    static func write(_ value: String, into buf: inout [UInt8]) {
        let len = Int32(value.utf8.count)
        writeInt(&buf, len)
        writeBytes(&buf, value.utf8)
    }
}

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
private struct FfiConverterData: FfiConverterRustBuffer {
    typealias SwiftType = Data

    static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> Data {
        let len: Int32 = try readInt(&buf)
        return try Data(readBytes(&buf, count: Int(len)))
    }

    static func write(_ value: Data, into buf: inout [UInt8]) {
        let len = Int32(value.count)
        writeInt(&buf, len)
        writeBytes(&buf, value)
    }
}

public protocol ClawSessionProtocol: AnyObject {
    /**
     * Liveness round-trip → `Connected` (tunnel ready). NOT openable.
     */
    func healthPing() async throws -> SessionStatus

    /**
     * Decode + accept a credential as canonical CBOR. Refuses on parse
     * failure OR on a failed owner-signature / expiry check.
     */
    func loadCredential(credentialCbor: Data, nowUnix: UInt64) async throws -> SessionStatus

    /**
     * Block until one L3 packet arrives from the tunnel (steady-state
     * read loop). Health frames are skipped. Returns the packet bytes.
     */
    func receivePacket() async throws -> Data

    /**
     * Push one L3 packet down the tunnel (steady-state write loop).
     */
    func sendPacket(packet: Data) async throws

    /**
     * Dial the engine data tunnel + authenticate. Splits the socket into
     * read/write halves for the concurrent packet loops. Enters
     * `AwaitingFirstPacket`.
     * `session_token_cbor` is the host-signed proof-of-possession token
     * (canonical CBOR of a `SessionAuthToken`, signed by the guest device
     * key). The bridge forwards it in the auth envelope; the engine
     * verifies it against the credential's `guest_device_pub`, so a
     * stolen credential without this token is rejected.
     */
    func startSession(config: DataPlaneConfig, sessionTokenCbor: Data) async throws -> StartSessionOutcome

    func status() async -> SessionStatus

    /**
     * Stop the session. Idempotent. Drops both tunnel halves so any
     * in-flight `receive_packet` errors out and the loop exits.
     */
    func stopSession(reason: String) async -> SessionStatus

    /**
     * Send a real probe packet that the engine ROUTES to the target
     * service, and await the target's response → `TargetVerified` (the
     * only openable state). The engine has no packet-echo path, so a
     * response can only mean the target was reached. Call after
     * `health_ping`, before the steady-state packet loop.
     */
    func verifyTargetPath() async throws -> SessionStatus
}

open class ClawSession:
    ClawSessionProtocol
{
    fileprivate let pointer: UnsafeMutableRawPointer!

    // Used to instantiate a [FFIObject] without an actual pointer, for fakes in tests, mostly.
    #if swift(>=5.8)
        @_documentation(visibility: private)
    #endif
    public struct NoPointer {
        public init() {}
    }

    // TODO: We'd like this to be `private` but for Swifty reasons,
    // we can't implement `FfiConverter` without making this `required` and we can't
    // make it `required` without making it `public`.
    public required init(unsafeFromRawPointer pointer: UnsafeMutableRawPointer) {
        self.pointer = pointer
    }

    // This constructor can be used to instantiate a fake object.
    // - Parameter noPointer: Placeholder value so we can have a constructor separate from the default empty one that may be implemented for classes extending [FFIObject].
    //
    // - Warning:
    //     Any object instantiated with this constructor cannot be passed to an actual Rust-backed object. Since there isn't a backing [Pointer] the FFI lower functions will crash.
    #if swift(>=5.8)
        @_documentation(visibility: private)
    #endif
    public init(noPointer _: NoPointer) {
        pointer = nil
    }

    #if swift(>=5.8)
        @_documentation(visibility: private)
    #endif
    public func uniffiClonePointer() -> UnsafeMutableRawPointer {
        return try! rustCall { uniffi_claw_share_bridge_rs_fn_clone_clawsession(self.pointer, $0) }
    }

    public convenience init() {
        let pointer =
            try! rustCall {
                uniffi_claw_share_bridge_rs_fn_constructor_clawsession_new($0)
            }
        self.init(unsafeFromRawPointer: pointer)
    }

    deinit {
        guard let pointer = pointer else {
            return
        }

        try! rustCall { uniffi_claw_share_bridge_rs_fn_free_clawsession(pointer, $0) }
    }

    /**
     * Liveness round-trip → `Connected` (tunnel ready). NOT openable.
     */
    open func healthPing() async throws -> SessionStatus {
        return
            try await uniffiRustCallAsync(
                rustFutureFunc: {
                    uniffi_claw_share_bridge_rs_fn_method_clawsession_health_ping(
                        self.uniffiClonePointer()
                    )
                },
                pollFunc: ffi_claw_share_bridge_rs_rust_future_poll_rust_buffer,
                completeFunc: ffi_claw_share_bridge_rs_rust_future_complete_rust_buffer,
                freeFunc: ffi_claw_share_bridge_rs_rust_future_free_rust_buffer,
                liftFunc: FfiConverterTypeSessionStatus.lift,
                errorHandler: FfiConverterTypeBridgeError.lift
            )
    }

    /**
     * Decode + accept a credential as canonical CBOR. Refuses on parse
     * failure OR on a failed owner-signature / expiry check.
     */
    open func loadCredential(credentialCbor: Data, nowUnix: UInt64) async throws -> SessionStatus {
        return
            try await uniffiRustCallAsync(
                rustFutureFunc: {
                    uniffi_claw_share_bridge_rs_fn_method_clawsession_load_credential(
                        self.uniffiClonePointer(),
                        FfiConverterData.lower(credentialCbor), FfiConverterUInt64.lower(nowUnix)
                    )
                },
                pollFunc: ffi_claw_share_bridge_rs_rust_future_poll_rust_buffer,
                completeFunc: ffi_claw_share_bridge_rs_rust_future_complete_rust_buffer,
                freeFunc: ffi_claw_share_bridge_rs_rust_future_free_rust_buffer,
                liftFunc: FfiConverterTypeSessionStatus.lift,
                errorHandler: FfiConverterTypeBridgeError.lift
            )
    }

    /**
     * Block until one L3 packet arrives from the tunnel (steady-state
     * read loop). Health frames are skipped. Returns the packet bytes.
     */
    open func receivePacket() async throws -> Data {
        return
            try await uniffiRustCallAsync(
                rustFutureFunc: {
                    uniffi_claw_share_bridge_rs_fn_method_clawsession_receive_packet(
                        self.uniffiClonePointer()
                    )
                },
                pollFunc: ffi_claw_share_bridge_rs_rust_future_poll_rust_buffer,
                completeFunc: ffi_claw_share_bridge_rs_rust_future_complete_rust_buffer,
                freeFunc: ffi_claw_share_bridge_rs_rust_future_free_rust_buffer,
                liftFunc: FfiConverterData.lift,
                errorHandler: FfiConverterTypeBridgeError.lift
            )
    }

    /**
     * Push one L3 packet down the tunnel (steady-state write loop).
     */
    open func sendPacket(packet: Data) async throws {
        return
            try await uniffiRustCallAsync(
                rustFutureFunc: {
                    uniffi_claw_share_bridge_rs_fn_method_clawsession_send_packet(
                        self.uniffiClonePointer(),
                        FfiConverterData.lower(packet)
                    )
                },
                pollFunc: ffi_claw_share_bridge_rs_rust_future_poll_void,
                completeFunc: ffi_claw_share_bridge_rs_rust_future_complete_void,
                freeFunc: ffi_claw_share_bridge_rs_rust_future_free_void,
                liftFunc: { $0 },
                errorHandler: FfiConverterTypeBridgeError.lift
            )
    }

    /**
     * Dial the engine data tunnel + authenticate. Splits the socket into
     * read/write halves for the concurrent packet loops. Enters
     * `AwaitingFirstPacket`.
     * `session_token_cbor` is the host-signed proof-of-possession token
     * (canonical CBOR of a `SessionAuthToken`, signed by the guest device
     * key). The bridge forwards it in the auth envelope; the engine
     * verifies it against the credential's `guest_device_pub`, so a
     * stolen credential without this token is rejected.
     */
    open func startSession(config: DataPlaneConfig, sessionTokenCbor: Data) async throws -> StartSessionOutcome {
        return
            try await uniffiRustCallAsync(
                rustFutureFunc: {
                    uniffi_claw_share_bridge_rs_fn_method_clawsession_start_session(
                        self.uniffiClonePointer(),
                        FfiConverterTypeDataPlaneConfig.lower(config), FfiConverterData.lower(sessionTokenCbor)
                    )
                },
                pollFunc: ffi_claw_share_bridge_rs_rust_future_poll_rust_buffer,
                completeFunc: ffi_claw_share_bridge_rs_rust_future_complete_rust_buffer,
                freeFunc: ffi_claw_share_bridge_rs_rust_future_free_rust_buffer,
                liftFunc: FfiConverterTypeStartSessionOutcome.lift,
                errorHandler: FfiConverterTypeBridgeError.lift
            )
    }

    open func status() async -> SessionStatus {
        return
            try! await uniffiRustCallAsync(
                rustFutureFunc: {
                    uniffi_claw_share_bridge_rs_fn_method_clawsession_status(
                        self.uniffiClonePointer()
                    )
                },
                pollFunc: ffi_claw_share_bridge_rs_rust_future_poll_rust_buffer,
                completeFunc: ffi_claw_share_bridge_rs_rust_future_complete_rust_buffer,
                freeFunc: ffi_claw_share_bridge_rs_rust_future_free_rust_buffer,
                liftFunc: FfiConverterTypeSessionStatus.lift,
                errorHandler: nil
            )
    }

    /**
     * Stop the session. Idempotent. Drops both tunnel halves so any
     * in-flight `receive_packet` errors out and the loop exits.
     */
    open func stopSession(reason: String) async -> SessionStatus {
        return
            try! await uniffiRustCallAsync(
                rustFutureFunc: {
                    uniffi_claw_share_bridge_rs_fn_method_clawsession_stop_session(
                        self.uniffiClonePointer(),
                        FfiConverterString.lower(reason)
                    )
                },
                pollFunc: ffi_claw_share_bridge_rs_rust_future_poll_rust_buffer,
                completeFunc: ffi_claw_share_bridge_rs_rust_future_complete_rust_buffer,
                freeFunc: ffi_claw_share_bridge_rs_rust_future_free_rust_buffer,
                liftFunc: FfiConverterTypeSessionStatus.lift,
                errorHandler: nil
            )
    }

    /**
     * Send a real probe packet that the engine ROUTES to the target
     * service, and await the target's response → `TargetVerified` (the
     * only openable state). The engine has no packet-echo path, so a
     * response can only mean the target was reached. Call after
     * `health_ping`, before the steady-state packet loop.
     */
    open func verifyTargetPath() async throws -> SessionStatus {
        return
            try await uniffiRustCallAsync(
                rustFutureFunc: {
                    uniffi_claw_share_bridge_rs_fn_method_clawsession_verify_target_path(
                        self.uniffiClonePointer()
                    )
                },
                pollFunc: ffi_claw_share_bridge_rs_rust_future_poll_rust_buffer,
                completeFunc: ffi_claw_share_bridge_rs_rust_future_complete_rust_buffer,
                freeFunc: ffi_claw_share_bridge_rs_rust_future_free_rust_buffer,
                liftFunc: FfiConverterTypeSessionStatus.lift,
                errorHandler: FfiConverterTypeBridgeError.lift
            )
    }
}

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
public struct FfiConverterTypeClawSession: FfiConverter {
    typealias FfiType = UnsafeMutableRawPointer
    typealias SwiftType = ClawSession

    public static func lift(_ pointer: UnsafeMutableRawPointer) throws -> ClawSession {
        return ClawSession(unsafeFromRawPointer: pointer)
    }

    public static func lower(_ value: ClawSession) -> UnsafeMutableRawPointer {
        return value.uniffiClonePointer()
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> ClawSession {
        let v: UInt64 = try readInt(&buf)
        // The Rust code won't compile if a pointer won't fit in a UInt64.
        // We have to go via `UInt` because that's the thing that's the size of a pointer.
        let ptr = UnsafeMutableRawPointer(bitPattern: UInt(truncatingIfNeeded: v))
        if ptr == nil {
            throw UniffiInternalError.unexpectedNullPointer
        }
        return try lift(ptr!)
    }

    public static func write(_ value: ClawSession, into buf: inout [UInt8]) {
        // This fiddling is because `Int` is the thing that's the same size as a pointer.
        // The Rust code won't compile if a pointer won't fit in a `UInt64`.
        writeInt(&buf, UInt64(bitPattern: Int64(Int(bitPattern: lower(value)))))
    }
}

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
public func FfiConverterTypeClawSession_lift(_ pointer: UnsafeMutableRawPointer) throws -> ClawSession {
    return try FfiConverterTypeClawSession.lift(pointer)
}

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
public func FfiConverterTypeClawSession_lower(_ value: ClawSession) -> UnsafeMutableRawPointer {
    return FfiConverterTypeClawSession.lower(value)
}

/**
 * Where the engine's claw data tunnel is reachable.
 */
public struct DataPlaneConfig {
    public var host: String
    public var port: UInt16

    /// Default memberwise initializers are never public by default, so we
    /// declare one manually.
    public init(host: String, port: UInt16) {
        self.host = host
        self.port = port
    }
}

extension DataPlaneConfig: Equatable, Hashable {
    public static func == (lhs: DataPlaneConfig, rhs: DataPlaneConfig) -> Bool {
        if lhs.host != rhs.host {
            return false
        }
        if lhs.port != rhs.port {
            return false
        }
        return true
    }

    public func hash(into hasher: inout Hasher) {
        hasher.combine(host)
        hasher.combine(port)
    }
}

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
public struct FfiConverterTypeDataPlaneConfig: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> DataPlaneConfig {
        return
            try DataPlaneConfig(
                host: FfiConverterString.read(from: &buf),
                port: FfiConverterUInt16.read(from: &buf)
            )
    }

    public static func write(_ value: DataPlaneConfig, into buf: inout [UInt8]) {
        FfiConverterString.write(value.host, into: &buf)
        FfiConverterUInt16.write(value.port, into: &buf)
    }
}

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
public func FfiConverterTypeDataPlaneConfig_lift(_ buf: RustBuffer) throws -> DataPlaneConfig {
    return try FfiConverterTypeDataPlaneConfig.lift(buf)
}

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
public func FfiConverterTypeDataPlaneConfig_lower(_ value: DataPlaneConfig) -> RustBuffer {
    return FfiConverterTypeDataPlaneConfig.lower(value)
}

/**
 * Handshake result the bridge reports back after `start_session`.
 */
public struct StartSessionOutcome {
    public var meshIpv6: String
    public var mtu: UInt16
    /**
     * Engine-assigned session id (stable per credential/slot).
     */
    public var sessionId: String
    /**
     * Always `AwaitingFirstPacket`.
     */
    public var status: SessionStatus

    /// Default memberwise initializers are never public by default, so we
    /// declare one manually.
    public init(meshIpv6: String, mtu: UInt16,
                /* 
                    * Engine-assigned session id (stable per credential/slot).
                    */ sessionId: String,
                /* 
                    * Always `AwaitingFirstPacket`.
                    */ status: SessionStatus)
    {
        self.meshIpv6 = meshIpv6
        self.mtu = mtu
        self.sessionId = sessionId
        self.status = status
    }
}

extension StartSessionOutcome: Equatable, Hashable {
    public static func == (lhs: StartSessionOutcome, rhs: StartSessionOutcome) -> Bool {
        if lhs.meshIpv6 != rhs.meshIpv6 {
            return false
        }
        if lhs.mtu != rhs.mtu {
            return false
        }
        if lhs.sessionId != rhs.sessionId {
            return false
        }
        if lhs.status != rhs.status {
            return false
        }
        return true
    }

    public func hash(into hasher: inout Hasher) {
        hasher.combine(meshIpv6)
        hasher.combine(mtu)
        hasher.combine(sessionId)
        hasher.combine(status)
    }
}

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
public struct FfiConverterTypeStartSessionOutcome: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> StartSessionOutcome {
        return
            try StartSessionOutcome(
                meshIpv6: FfiConverterString.read(from: &buf),
                mtu: FfiConverterUInt16.read(from: &buf),
                sessionId: FfiConverterString.read(from: &buf),
                status: FfiConverterTypeSessionStatus.read(from: &buf)
            )
    }

    public static func write(_ value: StartSessionOutcome, into buf: inout [UInt8]) {
        FfiConverterString.write(value.meshIpv6, into: &buf)
        FfiConverterUInt16.write(value.mtu, into: &buf)
        FfiConverterString.write(value.sessionId, into: &buf)
        FfiConverterTypeSessionStatus.write(value.status, into: &buf)
    }
}

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
public func FfiConverterTypeStartSessionOutcome_lift(_ buf: RustBuffer) throws -> StartSessionOutcome {
    return try FfiConverterTypeStartSessionOutcome.lift(buf)
}

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
public func FfiConverterTypeStartSessionOutcome_lower(_ value: StartSessionOutcome) -> RustBuffer {
    return FfiConverterTypeStartSessionOutcome.lower(value)
}

public enum BridgeError {
    case CredentialDecode(message: String)

    case CredentialInvalid(message: String)

    case NoSession(message: String)

    case HandshakeFailed(message: String)

    case HealthRoundTripFailed(message: String)

    case PacketRoundTripFailed(message: String)

    case TokenInvalid(message: String)

    case TransportFailed(message: String)

    case Internal(message: String)
}

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
public struct FfiConverterTypeBridgeError: FfiConverterRustBuffer {
    typealias SwiftType = BridgeError

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> BridgeError {
        let variant: Int32 = try readInt(&buf)
        switch variant {
        case 1: return try .CredentialDecode(
                message: FfiConverterString.read(from: &buf)
            )

        case 2: return try .CredentialInvalid(
                message: FfiConverterString.read(from: &buf)
            )

        case 3: return try .NoSession(
                message: FfiConverterString.read(from: &buf)
            )

        case 4: return try .HandshakeFailed(
                message: FfiConverterString.read(from: &buf)
            )

        case 5: return try .HealthRoundTripFailed(
                message: FfiConverterString.read(from: &buf)
            )

        case 6: return try .PacketRoundTripFailed(
                message: FfiConverterString.read(from: &buf)
            )

        case 7: return try .TokenInvalid(
                message: FfiConverterString.read(from: &buf)
            )

        case 8: return try .TransportFailed(
                message: FfiConverterString.read(from: &buf)
            )

        case 9: return try .Internal(
                message: FfiConverterString.read(from: &buf)
            )

        default: throw UniffiInternalError.unexpectedEnumCase
        }
    }

    public static func write(_ value: BridgeError, into buf: inout [UInt8]) {
        switch value {
        case .CredentialDecode(_ /* message is ignored*/ ):
            writeInt(&buf, Int32(1))
        case .CredentialInvalid(_ /* message is ignored*/ ):
            writeInt(&buf, Int32(2))
        case .NoSession(_ /* message is ignored*/ ):
            writeInt(&buf, Int32(3))
        case .HandshakeFailed(_ /* message is ignored*/ ):
            writeInt(&buf, Int32(4))
        case .HealthRoundTripFailed(_ /* message is ignored*/ ):
            writeInt(&buf, Int32(5))
        case .PacketRoundTripFailed(_ /* message is ignored*/ ):
            writeInt(&buf, Int32(6))
        case .TokenInvalid(_ /* message is ignored*/ ):
            writeInt(&buf, Int32(7))
        case .TransportFailed(_ /* message is ignored*/ ):
            writeInt(&buf, Int32(8))
        case .Internal(_ /* message is ignored*/ ):
            writeInt(&buf, Int32(9))
        }
    }
}

extension BridgeError: Equatable, Hashable {}

extension BridgeError: Foundation.LocalizedError {
    public var errorDescription: String? {
        String(reflecting: self)
    }
}

// Note that we don't yet support `indirect` for enums.
// See https://github.com/mozilla/uniffi-rs/issues/396 for further discussion.
/* 
 * Lifecycle of a claw session as observed by the bridge.
 *
 * `Connected` (after `health_ping`) means the tunnel is READY.
 * `PacketVerified` (after `verify_packet_path`) means a real packet
 * crossed the tunnel and returned — the ONLY openable state.
 */

public enum SessionStatus {
    case idle
    case credentialReady
    case dialing
    /**
     * Handshake done; no health round-trip yet.
     */
    case awaitingFirstPacket
    /**
     * Health echo succeeded — tunnel ready + transport works, but NOT
     * openable (the tunnel echoing bytes is not proof a target exists).
     */
    case connected(sinceUnix: UInt64)
    /**
     * A packet was ROUTED to the real target service and its response
     * came back — user traffic reaches the target. The ONLY openable
     * state. (The engine has no packet-echo path, so a packet response
     * can only mean the target was reached.)
     */
    case targetVerified(sinceUnix: UInt64)
    case stopped(reason: String)
    case failed(reason: String)
}

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
public struct FfiConverterTypeSessionStatus: FfiConverterRustBuffer {
    typealias SwiftType = SessionStatus

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> SessionStatus {
        let variant: Int32 = try readInt(&buf)
        switch variant {
        case 1: return .idle

        case 2: return .credentialReady

        case 3: return .dialing

        case 4: return .awaitingFirstPacket

        case 5: return try .connected(sinceUnix: FfiConverterUInt64.read(from: &buf))

        case 6: return try .targetVerified(sinceUnix: FfiConverterUInt64.read(from: &buf))

        case 7: return try .stopped(reason: FfiConverterString.read(from: &buf))

        case 8: return try .failed(reason: FfiConverterString.read(from: &buf))

        default: throw UniffiInternalError.unexpectedEnumCase
        }
    }

    public static func write(_ value: SessionStatus, into buf: inout [UInt8]) {
        switch value {
        case .idle:
            writeInt(&buf, Int32(1))

        case .credentialReady:
            writeInt(&buf, Int32(2))

        case .dialing:
            writeInt(&buf, Int32(3))

        case .awaitingFirstPacket:
            writeInt(&buf, Int32(4))

        case let .connected(sinceUnix):
            writeInt(&buf, Int32(5))
            FfiConverterUInt64.write(sinceUnix, into: &buf)

        case let .targetVerified(sinceUnix):
            writeInt(&buf, Int32(6))
            FfiConverterUInt64.write(sinceUnix, into: &buf)

        case let .stopped(reason):
            writeInt(&buf, Int32(7))
            FfiConverterString.write(reason, into: &buf)

        case let .failed(reason):
            writeInt(&buf, Int32(8))
            FfiConverterString.write(reason, into: &buf)
        }
    }
}

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
public func FfiConverterTypeSessionStatus_lift(_ buf: RustBuffer) throws -> SessionStatus {
    return try FfiConverterTypeSessionStatus.lift(buf)
}

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
public func FfiConverterTypeSessionStatus_lower(_ value: SessionStatus) -> RustBuffer {
    return FfiConverterTypeSessionStatus.lower(value)
}

extension SessionStatus: Equatable, Hashable {}

private let UNIFFI_RUST_FUTURE_POLL_READY: Int8 = 0
private let UNIFFI_RUST_FUTURE_POLL_MAYBE_READY: Int8 = 1

private let uniffiContinuationHandleMap = UniffiHandleMap<UnsafeContinuation<Int8, Never>>()

private func uniffiRustCallAsync<F, T>(
    rustFutureFunc: () -> UInt64,
    pollFunc: (UInt64, @escaping UniffiRustFutureContinuationCallback, UInt64) -> Void,
    completeFunc: (UInt64, UnsafeMutablePointer<RustCallStatus>) -> F,
    freeFunc: (UInt64) -> Void,
    liftFunc: (F) throws -> T,
    errorHandler: ((RustBuffer) throws -> Swift.Error)?
) async throws -> T {
    // Make sure to call uniffiEnsureInitialized() since future creation doesn't have a
    // RustCallStatus param, so doesn't use makeRustCall()
    uniffiEnsureInitialized()
    let rustFuture = rustFutureFunc()
    defer {
        freeFunc(rustFuture)
    }
    var pollResult: Int8
    repeat {
        pollResult = await withUnsafeContinuation {
            pollFunc(
                rustFuture,
                uniffiFutureContinuationCallback,
                uniffiContinuationHandleMap.insert(obj: $0)
            )
        }
    } while pollResult != UNIFFI_RUST_FUTURE_POLL_READY

    return try liftFunc(makeRustCall(
        { completeFunc(rustFuture, $0) },
        errorHandler: errorHandler
    ))
}

/// Callback handlers for an async calls.  These are invoked by Rust when the future is ready.  They
/// lift the return value or error and resume the suspended function.
private func uniffiFutureContinuationCallback(handle: UInt64, pollResult: Int8) {
    if let continuation = try? uniffiContinuationHandleMap.remove(handle: handle) {
        continuation.resume(returning: pollResult)
    } else {
        print("uniffiFutureContinuationCallback invalid handle")
    }
}

/**
 * Spin up an in-process loopback tunnel on `127.0.0.1:0` and return its
 * port. Self-test helper running the REAL [`dt::serve_connection`]:
 * health echoes, and packets are ROUTED (via [`dt::TcpForwardRouter`])
 * to a separate in-process TCP target that replies `TARGET-ACK`. So a
 * Swift test can drive the full path — health → routed packet → target
 * response — without a real engine. Credential *authorization* is
 * permissive (the token/credential matrix is covered by the engine-side
 * tests); but packets genuinely traverse to the separate target socket,
 * so `verify_target_path` exercises real routing, not tunnel echo.
 */
public func startLoopbackEchoServer() async throws -> UInt16 {
    return
        try await uniffiRustCallAsync(
            rustFutureFunc: {
                uniffi_claw_share_bridge_rs_fn_func_start_loopback_echo_server(
                )
            },
            pollFunc: ffi_claw_share_bridge_rs_rust_future_poll_u16,
            completeFunc: ffi_claw_share_bridge_rs_rust_future_complete_u16,
            freeFunc: ffi_claw_share_bridge_rs_rust_future_free_u16,
            liftFunc: FfiConverterUInt16.lift,
            errorHandler: FfiConverterTypeBridgeError.lift
        )
}

private enum InitializationResult {
    case ok
    case contractVersionMismatch
    case apiChecksumMismatch
}

/// Use a global variable to perform the versioning checks. Swift ensures that
/// the code inside is only computed once.
private var initializationResult: InitializationResult = {
    // Get the bindings contract version from our ComponentInterface
    let bindings_contract_version = 26
    // Get the scaffolding contract version by calling the into the dylib
    let scaffolding_contract_version = ffi_claw_share_bridge_rs_uniffi_contract_version()
    if bindings_contract_version != scaffolding_contract_version {
        return InitializationResult.contractVersionMismatch
    }
    if uniffi_claw_share_bridge_rs_checksum_func_start_loopback_echo_server() != 43540 {
        return InitializationResult.apiChecksumMismatch
    }
    if uniffi_claw_share_bridge_rs_checksum_method_clawsession_health_ping() != 54432 {
        return InitializationResult.apiChecksumMismatch
    }
    if uniffi_claw_share_bridge_rs_checksum_method_clawsession_load_credential() != 35020 {
        return InitializationResult.apiChecksumMismatch
    }
    if uniffi_claw_share_bridge_rs_checksum_method_clawsession_receive_packet() != 5864 {
        return InitializationResult.apiChecksumMismatch
    }
    if uniffi_claw_share_bridge_rs_checksum_method_clawsession_send_packet() != 791 {
        return InitializationResult.apiChecksumMismatch
    }
    if uniffi_claw_share_bridge_rs_checksum_method_clawsession_start_session() != 21457 {
        return InitializationResult.apiChecksumMismatch
    }
    if uniffi_claw_share_bridge_rs_checksum_method_clawsession_status() != 22157 {
        return InitializationResult.apiChecksumMismatch
    }
    if uniffi_claw_share_bridge_rs_checksum_method_clawsession_stop_session() != 27468 {
        return InitializationResult.apiChecksumMismatch
    }
    if uniffi_claw_share_bridge_rs_checksum_method_clawsession_verify_target_path() != 53402 {
        return InitializationResult.apiChecksumMismatch
    }
    if uniffi_claw_share_bridge_rs_checksum_constructor_clawsession_new() != 29248 {
        return InitializationResult.apiChecksumMismatch
    }

    return InitializationResult.ok
}()

private func uniffiEnsureInitialized() {
    switch initializationResult {
    case .ok:
        break
    case .contractVersionMismatch:
        fatalError("UniFFI contract version mismatch: try cleaning and rebuilding your project")
    case .apiChecksumMismatch:
        fatalError("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    }
}

// swiftlint:enable all
